[package]
name = "fubuki-oauth-proxy"
version = "0.1.0"
authors = ["nnazo <jacobcurtis2266@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.2.3"
reqwest = { version = "0.10.6", features = ["json"] }
tokio = { version = "0.2.21", features = ["full"] }
config = "0.10.1"
hyper = "0.13.6"